seedwing-io/seedwing-policy

.github/workflows/ci.yaml
README.adoc

feat: add ci

---

seedwing-policy-engine/src/core/kafka/mod.rs
seedwing-policy-engine/src/core/kafka/opa.dog
seedwing-policy-engine/src/core/mod.rs
seedwing-policy-engine/src/lang/hir/mod.rs
seedwing-policy-engine/src/runtime/sources.rs
seedwing-policy-server/src/policy.rs

Based on payload queried from the OpaAuthorizer as for https://www.openpolicyagent.org/docs/latest/kafka-authorization/

feat: add policy definition matching kafka authorizer plugin request

---

seedwing-policy-engine/src/core/base64/Base64Encode.adoc
seedwing-policy-engine/src/core/base64/mod.rs
seedwing-policy-engine/src/core/x509/convert.rs

Maybe there is a better way for the octet thing. But this worked for me.

New fields for X509 certificates and a way to test octets

---

seedwing-policy-engine/src/core/list/Head.adoc
seedwing-policy-engine/src/core/list/Tail.adoc
seedwing-policy-engine/src/core/list/head.rs
seedwing-policy-engine/src/core/list/mod.rs
seedwing-policy-engine/src/core/list/tail.rs
seedwing-policy-engine/src/core/mod.rs
seedwing-policy-engine/src/core/pem/mod.rs
seedwing-policy-engine/src/core/x509/mod.rs
seedwing-policy-engine/src/lang/hir/mod.rs
seedwing-policy-engine/src/value/mod.rs

**NOTE:** This PR is based on #30, only the top commit is necessary for this PR.

Add list::Head and list::Tail functions

---

README.md

Update readme with nodejs requirement

---

seedwing-policy-engine/src/core/openvex/mod.rs
seedwing-policy-engine/src/core/osv/osv.rs
seedwing-policy-engine/src/core/osv/purl.rs

This improves the speed for large BOMs, but removes some information from the output, so it will be harder to identify the affected component.

feat: support using batch API for queries

---

seedwing-policy-server/src/ui/_playground.html
seedwing-policy-server/src/ui/_type.html
seedwing-policy-server/web/copy-assets.sh
seedwing-policy-server/web/package.json
seedwing-policy-server/web/yarn.lock

fixes #3
@bobmcwhirter Texmate grammar is not supported in the js-embedded version of monaco

Use the monaco editor in the playground and experiments

---

seedwing-policy-engine/src/core/lang/map.rs

If input is not a list, it becomes the only element in returned list.

fix: lang::map always returns a list now

---

server/src/api/format.rs
server/src/api/mod.rs

This might not be all of it, but it's a start.

refactor: bring back output encoding

---

.devcontainer.json
.github/workflows/dev_container.yaml
Containerfile

Provide a ready to go development environment :
```shell
[seedwing-policy] toolbox create seedwing --image ghcr.io/jbtrystram/devcontainer
Created container: seedwing
Enter with: toolbox enter seedwing
[seedwing-policy] toolbox enter seedwing   
⬢[jibou@toolbox seedwing-policy]$
⬢[jibou@toolbox seedwing-policy]$ cd seedwing-policy-server/
⬢[jibou@toolbox seedwing-policy-server]$ cargo run
Compiling seedwing-policy-server v0.1.0-alpha.2 (/home/jibou/github/seedwing/seedwing-policy/seedwing-policy-server)
Finished dev [unoptimized + debuginfo] target(s) in 7.11s
```

Create a devcontainer image

---

Cargo.lock
engine/src/core/string/concat.adoc
engine/src/core/string/concat.rs
engine/src/core/string/length.rs
engine/src/core/string/mod.rs
frontend/Cargo.lock

feat: add string::append, string::prepend and string::count

---

engine/src/core/base64/mod.rs
engine/src/core/mod.rs
engine/src/lang/hir/mod.rs
engine/src/lang/lir/mod.rs
engine/src/lang/mir/mod.rs
engine/src/runtime/mod.rs
server/src/api/mod.rs
server/src/api/openapi.rs

This add the concept of examples, allowing pattern authors to provide examples for the user to try out. This also gets mapped to the Swagger UI.

feat: add concept of examples

---

Cargo.lock
engine/Cargo.toml
engine/src/core/mod.rs
engine/src/core/slsa/example1.json
engine/src/core/slsa/mod.rs
engine/src/core/slsa/provenance-v1_0.dog
engine/src/lang/hir/mod.rs
engine/src/lib.rs
engine/src/runtime/metadata.rs
engine/src/runtime/mod.rs
frontend/src/pages/policy/mod.rs

Initial support for the SLSA 1.0-rc1 provenance schema.

Slsa prov schema

---

.github/workflows/release.yaml
engine/src/lib.rs
frontend/src/about.rs
frontend/src/console.rs
frontend/src/main.rs
server/src/api/mod.rs
server/src/api/openapi.rs
server/src/lib.rs
swio/src/cli.rs

feat: add server and client version to the cli, server and ui

---

engine/src/runtime/response.rs
frontend/src/common/eval.rs

Not sure I love the default [de]serialization yet

feat: distinguish between pattern and field names in responses

---

engine/src/core/debug/delay.rs
engine/src/core/lang/map-or-null.adoc
engine/src/core/lang/map.adoc
engine/src/core/lang/map.rs
engine/src/core/lang/map_or_null.rs
engine/src/core/lang/mod.rs
engine/src/runtime/response.rs

* Ensure map output contains the name number of elements in output list
* Change map output to provide information about why/why not element matched per-element
* Provide map-or-null  function which only outputs the values without any match information

Fixed number of list elems

---

engine/src/core/list/filter.adoc
engine/src/core/list/filter.rs
engine/src/core/list/mod.rs

Accepts lists as input and outputs the input values that matched the pattern parameter

feat: add list::filter

---

engine/src/runtime/response.rs
server/src/api/format.rs
server/src/api/mod.rs

Fixes #177
Previous "minimal" behavior should be available by passing `?select=output`.

feat: introduce query param to filter fields in response

---

swio/README.md
swio/src/command/eval.rs

Default fields are "name,severity,reason,rationale"
Fixes #195

feat: add --select option to eval to control output

---

docs/modules/policies/nav.adoc
docs/modules/policies/pages/spdx/index.adoc
docs/modules/policies/pages/spdx/v2_2/index.adoc
docs/modules/policies/pages/spdx/v2_3/index.adoc
engine/src/core/spdx/expr.adoc
engine/src/core/spdx/license.rs
engine/src/core/spdx/mod.rs
engine/src/core/spdx/spdx-v2.2.dog
engine/src/core/spdx/spdx-v2.3.dog
engine/test-data/spdx/v2_2_predicate.json
engine/test-data/spdx/v2_2_statement.json
engine/test-data/spdx/v2_3_predicate.json

This commit adds patterns for SPDX v2.2/v2.3 statements.
Closes: https://github.com/seedwing-io/seedwing-policy/issues/192

feat: add pattern for SPDX statements

---

Cargo.lock
Cargo.toml
engine/Cargo.toml
engine/src/runtime/response/mod.rs
frontend/Cargo.lock
server/Cargo.toml
server/src/api/format.rs
swio/Cargo.toml

Cleans up the format code a bit in the server.

refactor: use latest serde_view to handle unknown field errors
