seedwing-policy-engine/docs/dogma.adoc

This commit fixes a minor typo and also adds an escape to the # character as it is currently not being displayed properly.
Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>

Fix typos and escape # character

---

seedwing-policy-engine/Cargo.toml
seedwing-policy-engine/src/error_printer.rs
seedwing-policy-engine/src/runtime/mod.rs

This is achieved by using the thiserror crate, which was already in the dependency tree.
It helps with the integration with other crates, likes anyhow.
Also, fixed a typo.

feat: let the error types implement std::error::Error

---

seedwing-policy-engine/src/core/base64/Base64Encode.adoc
seedwing-policy-engine/src/core/base64/mod.rs
seedwing-policy-engine/src/core/x509/convert.rs
seedwing-policy-engine/src/value/mod.rs

This allows to drop all kinds of `.into()` calls, doing it implicitly.
Also it removes an unnecessary ownership on the get method parameter.
This PR builds on the changes of #27

refactor: make use of Object more ergonomic

---

.github/workflows/containers.yaml
.github/workflows/release.yaml

This PR brings the following changes to the release workflow:
* Let the container workflow only build (and upload) containers, but not publish
* Publish containers as part of the "publish" step
* Generate SBOMs for containers, attach, and sign
* Use JSON SBOMs
* Amend the crated SBOMs with the content of the yarn build (which is embedded in the binary)

Improve SBOMs for releases

---

Cargo.lock
seedwing-policy-server/Cargo.toml
seedwing-policy-server/src/main.rs
seedwing-policy-server/src/policy.rs
seedwing-policy-server/src/ui/json.rs
seedwing-policy-server/src/ui/mod.rs
seedwing-policy-server/src/ui/rationale.rs

Fixes #37 
We now support both the `application/x-www-form-urlencoded` and `application/json` content types. If the latter is specified for the request, a JSON response will be returned.
Here are sample outputs for both passing and failing requests:
```
[jim@fedora my-app]$ curl -i  -d @test.js http://localhost:8080/policy/proxy/context
HTTP/1.1 200 OK
content-length: 1188
date: Wed, 08 Feb 2023 17:17:55 GMT
<div><div class='entry satisfied'><div class='input'><pre>{
"hash": "bfcffcbb8f066268ac0816b1a1e5c49c202d8bac90706fe6edd9270596afac07",
"id": {
"_type": "m2",
"artifact_id": "maven-plugins",
"group_id": "org/apache/maven/plugins"
},
"license": null,
"repository_id": "m2",
"url": "https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/32/maven-plugins-32.pom" …
```

Return a JSON response upon request

---

seedwing-policy-engine/src/lang/hir/mod.rs

This commit removes what I believe is a duplicate insertion of `CompilationUnit` types.
The first insert is done in the iteration of the `uses`, using the `chain` function call. The second would then overwrite the first insert, but with a different `TypeName`.
Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>

Remove duplicate insert of CompilationUnit types

---

Cargo.lock
seedwing-policy-server/Cargo.toml
seedwing-policy-server/src/main.rs
seedwing-policy-server/src/policy.rs
seedwing-policy-server/src/ui/response.rs

Fixes #64 which is arguably not broken ;)
We've moved back to a single `evaluate` handler that will accept either JSON or YAML input -- if it fails one, it tries the other -- and could be easily extended to support TOML and other formats.
By default, the response will be in the format indicated by the `Content-Type` header of the request, i.e. if you pass in JSON, you get JSON back.
If you pass in an unrecognized `Content-Type`, e.g. `application/x-www-form-urlencoded`, you'll get HTML back.
You can override this default behavior to control the format of the response by including the `format` query param in the request, valid values being `html`, `json`, or `yaml`.

Accept YAML input and introduce 'format' query param

---

seedwing-policy-engine/src/lang/hir/mod.rs

This commit add cloning of the data_sources in World::clone.
The motivation for this is what without cloning the data_sources data::from usages will not work in the playground.
For example, currently the example in the documentation which uses data::from does not work:
```
pattern people = lang::or<*data::from<"people.json">>
```

Clone data_sources in World::clone

---

seedwing-policy-engine/src/data/mod.rs

This commit adds an error log when the target cannot be found.
The motivation for this is that currently it is easy to make a typo in the file name of a `data::from`, in which case the rule will fail but there is no information indicating that the file name could be incorrect.  Having this logging helps but long term we should probably Err on this situation.

Add error logging when target is not found

---

Cargo.lock
seedwing-policy-engine/Cargo.toml
seedwing-policy-engine/src/core/spdx/compatible.adoc
seedwing-policy-engine/src/core/spdx/compatible.rs
seedwing-policy-engine/src/core/spdx/mod.rs

The idea is to provide a list of valid licenses as parameters to verify against a license expression : 
`pattern only-copyleft = spdx::compatible<["OSL-2.0", "GPL-2.0", "CC-BY-SA-2.0"]>`
with the given input: `MIT OR Apache-2.0` would fail

Add a SPDX license expression parser

---

.github/workflows/ci.yaml
CONTRIBUTING.md
frontend/README.md
frontend/package-lock.json
server/embedded-frontend/build.rs

Moving on from yarn in favor of `npm ci` which guarantees repeatable builds by reading the lock file to recreate node_modules/

fix: don't trigger trunk build when yarn.lock is missing

---

engine/src/core/string/mod.rs
engine/src/core/string/split.adoc
engine/src/core/string/split.rs

This commit adds a function named `string::split` which enables a string to be split into a List.
Fixes: https://github.com/seedwing-io/seedwing-policy/issues/128

feat: add string::split function

---

engine/src/core/list/concat.adoc
engine/src/core/list/concat.rs
engine/src/core/list/mod.rs

This commit adds a function named `list::concat` which can concatenate an input list with a specified list. This function is also aliased to `list::append`.
Fixes: https://github.com/seedwing-io/seedwing-policy/issues/133

feat: add list::concat function

---

engine/src/core/list/count.adoc
engine/src/core/list/count.rs
engine/src/core/list/mod.rs

This commit adds a function named `list::count` which returns the length of a list. This same function is also aliased to `list::length`.
Fixes: https://github.com/seedwing-io/seedwing-policy/issues/121

feat: add list::count and list::length

---

engine/src/core/intoto/envelope.rs

This commit fixes a bug in `intoto:verify-envelope` where an empty list would returned if there were no `attesters `that matched the signature in the envelope. With this change this case will instead return `Output::None`.

fix: return Output::None if verified list is empty

---

engine/src/core/string/contains.rs

This commit updates the `string::contains` tests to use the test helper functions to reduce some boilerplate code.

test: update string contains.rs tests

---

Cargo.lock
docs/modules/policies/nav.adoc
docs/modules/policies/pages/semver/index.adoc
engine/Cargo.toml
engine/src/core/mod.rs
engine/src/core/semver/mod.rs
engine/src/core/semver/parse.adoc
engine/src/core/semver/parse.rs
engine/src/core/semver/semver.dog
engine/src/lang/hir/mod.rs
engine/src/value/mod.rs

Question for the person that will review this : 
Should the `semver.dog` file define the regexp for pre and build as well ? 
(Note that the above regexps are [probably wrong](https://regex101.com/r/vkijKf/1/))
```
pattern alphanumeric-identifier = string::regexp<"[a-Za-z0-9]">
pattern pre-release = alphanumeric-identifier
pattern build = alphanumeric-identifier
pattern semver = {
major: integer,
minor: integer,
patch: integer,
pre?: pre-release,
build?: build,
}
```

feat: add a semantic version parser. Fixes #158

---

Cargo.lock
engine/Cargo.toml

This commit removes danbev's revision and replaces it with the sigstore organisation and revision now that
https://github.com/sigstore/sigstore-rs/pull/239 has been merged.

chore: replace danbev revision with sigstore org

---

docs/modules/policies/pages/lang/index.adoc
engine/src/core/lang/traverse.adoc
engine/src/core/lang/traverse.rs

This commit adds an example and a test for the `lang::traverse` function.
The motivation for this is that I think I should use it with the SPDX patterns but was not sure how it worked. Hopefully this will be useful for others in the same situation.

docs: add example for lang::traverse

---

engine/src/core/csaf/v2_0.dog
engine/src/lang/parser/ty.rs
server/src/api/mod.rs

This commit adds a check to make sure that duplicate field names cause an error to be reported.
For example, with this commit starting the swio server will generate the following error:
```
$ cargo r --bin swio -- serve
Running `target/debug/swio serve`
Error: 
╭─[csaf:59:3]
│
59 │   contact_details?: string,
│   ────────────┬───────────  
│               ╰───────────── Duplicate field declared. Please remove one of "contact_details"
────╯
```
Fixes: https://github.com/seedwing-io/seedwing-policy/issues/181

fix: add check for duplicate field names

---

engine/src/core/intoto/envelope.rs

This commit adds support for sha512 digest algorithms in addition to the existing sha256.

Add sha512 support to intoto::verify-envelope

---

frontend/README.md

This commit contains a suggestion of adding the `--open` argument to trunk serve to automatically open the browser.

docs: update trunk serve command to use open

---

docs/modules/policies/pages/intoto/index.adoc
engine/src/core/intoto/verify-envelope.adoc

This commit tries to make the documentation for verify-envelope a little more readable.

Tidy up verify-envelope.adoc
